### ISSUE TITLE
Expected identifier

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/react-ie8#1]

**Comment by xcatliu** [comment]
http://stackoverflow.com/questions/17490398/ie8-expected-identifier-error
http://tiffanybbrown.com/2013/09/10/expected-identifier-bug-in-internet-explorer-8/
http://stackoverflow.com/questions/14448951/expected-identifier-error-from-ie8-and-ie7-when-object-has-new-as-property-n
http://stackoverflow.com/questions/5584249/javascript-vs-ie8-expected-identifier-string-or-number

**Comment by xcatliu** [comment]
Maybe caused by the `reserved words` using in IE8.

**Comment by xcatliu** [comment]
All third-party libraries which use `babel src --out-dir lib` have this problem.
I opened a issue: https://phabricator.babeljs.io/T6868

**Comment by xcatliu** [comment]
[es3ify](https://www.npmjs.com/package/es3ify) can deal with this problem if you are using browserify to bundle js.

Remember to use global transform:

```js
b.transform('es3ify', { global: true });
```

**Comment by xcatliu** [comment]
@yeatszhang What option should be set if we use `webpack` to bundle js?

**Comment by yeatszhang** [comment]
maybe use [es3ify-loader](https://github.com/sorrycc/es3ify-loader)

**Comment by xcatliu** [comment]
es3ify-loader with webpack example:
https://github.com/xcatliu/react-ie8/blob/master/examples/fetch-ie8/webpack.config.js#L17

**Comment by xcatliu** [comment]
Stackoverflow solution:
http://stackoverflow.com/questions/33512715/babel-6-0-20-modules-feature-not-work-in-ie8/33513000#33513000
