### ISSUE TITLE
抛出异常并未接住的错误

### ISSUE THREAD

**Issue by rubyless** [xcatliu/react-ie8#18]
throw new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);

这个错误怎么解决的，ie8下

**Comment by xcatliu** [comment]
是不是代码里面有 `Object.defineProperty`？

参考一下这个：
https://github.com/facebook/react/issues/3682
https://github.com/xcatliu/react-ie8/issues/2

**Comment by zuojj** [comment]
这个问题解决了吗？
```js
if (!supportsAccessors && (hasGetter || hasSetter)) {
    throw new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);
}
```
引发了异常但未捕获！！
