### ISSUE TITLE
使用hello world的example在IE8上依然出现Object.defineProperty问题

### ISSUE THREAD

**Issue by EdenLiang** [xcatliu/react-ie8#19]
使用hello world的example在IE8上依然出现Object.defineProperty问题，目测是babel6的打包问题，不过还没有解决，有看到说是用babel6-loose-mode来解决的。求更新

**Comment by xcatliu** [comment]
收到，我先看看是什么问题。

**Comment by xcatliu** [comment]
@EdenLiang 
我这边 hello world 的 example 在 IE8 下是正常的，我的 npm 和 node 版本：
```shell
npm -v
3.5.2
node -v
v4.2.2
```
你的版本是多少？

**Comment by EdenLiang** [comment]
webpack的问题，用生产环境就好了
