### ISSUE TITLE
Exception thrown and not caught

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/react-ie8#2]

**Comment by xcatliu** [comment]
Same issue: https://github.com/facebook/react/issues/3682

**Comment by xcatliu** [comment]
Related issue https://github.com/rackt/react-redux/issues/133

**Comment by xcatliu** [comment]
https://phabricator.babeljs.io/T2322

**Comment by xcatliu** [comment]
Related to https://github.com/rackt/react-redux/issues/227

**Comment by xcatliu** [comment]
`Object.defineProperty` should be wrapped in a `try catch` statement, like [react/src/shared/utils/canDefineProperty.js](https://github.com/facebook/react/blob/606aa61209aa1c4a867e10d024daf83c02800d76/src/shared/utils/canDefineProperty.js#L17)

**Comment by xcatliu** [comment]
Babel might transform your source to `Object.defineProperty`, be careful to use babel if you want to support ie8.
See https://github.com/rackt/react-redux/issues/227

**Comment by xcatliu** [comment]
/**
 * CANNOT use `import` to import `es5-shim`,
 * because `import` will be transformed to `Object.defineProperty` by babel,
 * `Object.defineProperty` doesn't exists in IE8,
 * (but will be polyfilled after `require('react-ie8')` executed).
 */

**Comment by Wind4** [comment]
Write ES6 code
```
import 'es5-shim';
import 'es5-shim/es5-sham';
import 'console-polyfill';
import 'es6-promise';
import 'fetch-ie8';

import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
  <div className="root">Hello</div>,
  document.getElementById('root'),
);
```
the babel will transform to:
```
'use strict';

require('es5-shim');
require('es5-shim/es5-sham');
require('console-polyfill');
require('es6-promise');
require('fetch-ie8');

var _react = require('react');
var _react2 = _interopRequireDefault(_react);
var _reactDom = require('react-dom');
var _reactDom2 = _interopRequireDefault(_reactDom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_reactDom2.default.render(_react2.default.createElement(
  'div',
  { className: 'root' },
  'Hello'
), document.getElementById('root'));
```
So, we can use the 'import' syntax.
