### ISSUE TITLE
报错了,不知道为啥...

### ISSUE THREAD

**Issue by gggin** [xcatliu/react-ie8#21]
![image](https://cloud.githubusercontent.com/assets/3293064/13943645/22e2fe9a-f039-11e5-9011-62d1f0c6b264.png)

**Comment by gggin** [comment]
使用了还有es5-shime的标准用法

new webpack.optimize.UglifyJsPlugin({
            compressor: {
                screw_ie8: true
            }
        })

**Comment by xcatliu** [comment]
可以看到报错内容吗？
代码不压缩的时候不会报错吗？

另外可以加上 sourceMap，这样可以看到压缩前的代码（不过好像 IE8 还不支持），详见：https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin

**Comment by gggin** [comment]
太贴心了 不压缩也会报错
![image](https://cloud.githubusercontent.com/assets/3293064/13943822/faf6a24a-f03a-11e5-8ada-5a3252717117.png)

![image](https://cloud.githubusercontent.com/assets/3293064/13943828/081c7fa8-f03b-11e5-992b-736cb2d3ead6.png)

**Comment by xcatliu** [comment]
看上去是 default 的问题。

default 是 es3 的关键字，不能直接作为 object 的 key，否则会在 IE8 里面报错。

可能需要 [es3ify-loader](https://github.com/sorrycc/es3ify-loader)

相关 issue：https://github.com/xcatliu/react-ie8/issues/1

**Comment by gggin** [comment]
Thank you!

**Comment by xcatliu** [comment]
You are welcome!
