### ISSUE TITLE
有关Object.defineProperties的问题

### ISSUE THREAD

**Issue by gggin** [xcatliu/react-ie8#24]
怎么才能让babel6 的import不生成Object.defineProperties的代码?

我这边已经干掉了好些依赖 不想使用es5-shim等polyfill 有办法么?

**Comment by xcatliu** [comment]
我也遇到过类似问题

可以看看这几个：
https://github.com/reactjs/react-redux/issues/133
https://github.com/reactjs/react-redux/issues/227
https://github.com/reactjs/react-redux/commit/a94ea6d01853d6262c278e9196246597153c97d9

不过这是以前的 babel，不知道现在还是不是这样。

**Comment by gggin** [comment]
真牛比啊!你演然是传说!

**Comment by xcatliu** [comment]
@gggin 过奖啦！

**Comment by gggin** [comment]
https://github.com/reactjs/redux/blob/master/.babelrc

参考这个babelrc 其中可以把env里面的plugins拿到外面来这样就没有Object.defineProperty了!

**Comment by sundayha** [comment]
@gggin 按照你的方法还是有啊。怎么解决，求指导
