### ISSUE TITLE
react-router-redux 4.x 中的Object.defineProperty问题

### ISSUE THREAD

**Issue by codering** [xcatliu/react-ie8#26]
你好，我看到react-router-redux 4.x 中发布的代码部分如下：
```js
Object.defineProperty(exports, 'LOCATION_CHANGE', {
    enumerable: true,
    get: function get() {
      return _reducer.LOCATION_CHANGE;
    }
  });
  Object.defineProperty(exports, 'routerReducer', {
    enumerable: true,
    get: function get() {
      return _reducer.routerReducer;
    }
  });
....
```
这样的代码 哪怕用了polyfill 也没法兼容IE8了吧 ?

**Comment by codering** [comment]
哈，看到官方的issue了， 等待修复中 https://github.com/reactjs/react-router-redux/issues/382

**Comment by dyf2015** [comment]
@codering 官方修复了吗？

**Comment by codering** [comment]
@dyf2015  我现在的做法是单独引用,  比如

```js
import syncHistoryWithStore  from 'react-router-redux/lib/sync'
import {routerReducer} from 'react-router-redux/lib/reducer'
```

你可用看下的源码index.js https://github.com/reactjs/react-router-redux/blob/master/src/index.js
```js

export syncHistoryWithStore from './sync'
export { LOCATION_CHANGE, routerReducer } from './reducer'

export {
  CALL_HISTORY_METHOD,
  push, replace, go, goBack, goForward,
  routerActions
} from './actions'
export routerMiddleware from './middleware'

```
按需单独引用就ok的。

**Comment by dyf2015** [comment]
感谢

发自我的 iPhone

在 2016年6月13日，09:54，Justin <notifications@github.com<mailto:notifications@github.com>> 写道：


@dyf2015<https://github.com/dyf2015> 我现在的做法是单独引用, 比如

import syncHistoryWithStore  from 'react-router-redux/lib/sync'
import {routerReducer} from 'react-router-redux/lib/reducer'

你可用看下的源码index.js https://github.com/reactjs/react-router-redux/blob/master/src/index.js

export syncHistoryWithStore from './sync'
export { LOCATION_CHANGE, routerReducer } from './reducer'

export {
  CALL_HISTORY_METHOD,
  push, replace, go, goBack, goForward,
  routerActions
} from './actions'
export routerMiddleware from './middleware'


按需单独引用就ok的。

―
