### ISSUE TITLE
IE8,firstChild.data.length undefind

### ISSUE THREAD

**Issue by LincWong** [xcatliu/react-ie8#28]
in IE8, this will be error.
`<div id="etDiv">
            <span>4444</span>
            <div class="abc"></div>
        </div>
        <script></script>
        <script type="text/javascript">
            var a = document.getElementById("etDiv");
            var b = a.firstChild;
            alert(b.data.length);
        </script>`

because b.data is undefined in IE8

**Comment by xcatliu** [comment]
You are right, b don't have an attribute 'data'. But this is not the issue about react.

Thank you all the time!
