### ISSUE TITLE
Script 5007 - Unable to get Value of the property 'location': object is null or undefined

### ISSUE THREAD

**Issue by hibearpanda** [xcatliu/react-ie8#29]
Currently trying to fix this react rendering issue in ie8 and ie9

It keeps bouncing this error, but the line it refers to (Line 108, Character 3) is just ReactDom.Render:

![screenshot 2016-05-26 18 21 49](https://cloud.githubusercontent.com/assets/11482515/15571675/bfebe4b4-236e-11e6-9ece-f06beaafcdba.png)

Do you have any suggestions on how to fix? Appreciate any advice you can give. Thank you!

**Comment by xcatliu** [comment]
Sorry I can't find any useful message according to the code above.

What is the error message? React has a good error reporting system, maybe we can find some clues from it.

Or you can submit a minimum version of your source code. And please write a step-by-step guide for how to reproduce the bug. It's better if I (or somebody) can repro the bug on my own machine

**Comment by xcatliu** [comment]
Sorry I missed the title of this issue.

**Comment by xcatliu** [comment]
According to the error message

> Unable to get Value of the property 'location': object is null or undefined

Something like `xxx.location.yyy` was being referenced but `xxx.location` was `undefined`, I guess you are using react-router and might have some trouble with the `browserHistory` API.

Can you submit a minimum version of your source code? And please write a step-by-step guide for how to reproduce the bug. It's better if I (or somebody) can repro the bug on my own machine.

**Comment by hibearpanda** [comment]
Yea, we think it is related to browserHistory as well. I'll see what I can do.
