### ISSUE TITLE
Babel transform  "export  xx from  'xxx' " to Object.defineProperty

### ISSUE THREAD

**Issue by nanjixiong218** [xcatliu/react-ie8#32]
"Babel transforms your import to Object.defineProperty which doesn't exist in IE8。"
 It should be 'export' ,not 'import' . IE8 has Object.defineProperty [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).
now Babel fixed the transform， but has another problem: Babel transform "export  xx from  'xxx' " to Object.defineProperty, like:
"
Object.defineProperty(exports, 'LOCATION_CHANGE', {
  enumerable: true,
  get: function get() {
    return _reducer.LOCATION_CHANGE;
  }
});
"
the accessor property not support in ie8.
so cannot use react-router-redux because it use "export  xx from  'xxx' ";

**Comment by xcatliu** [comment]
Thank you very much!

First yes you are right, babel fixed `import` issue. Now it's fine to use `import`. But I'll keep this issue in the `README.md`, for someone who are still use the old version of babel.

Second, I checked the link you gave, and found that I have made a mistake, IE8 did support `Object.defineProperty`, here is [what caniuse says](http://caniuse.com/#search=defineProperty):

> IE8 has virtually no ES5 support, but does support Object.defineProperty, Object.getOwnPropertyDescriptor, JSON parsing & Property access on strings

For this issue, I'll update the `README.md` later.

The last thing, I think you can report an issue (or create a pull-request) to `react-router-redux` if you want them to support IE8, although I don't know whether they will support or not.

Here is the related thing that I have done before:
https://github.com/xcatliu/react-ie8/issues/24
https://github.com/reactjs/react-redux/issues/133
https://github.com/reactjs/react-redux/issues/227
https://github.com/reactjs/react-redux/commit/a94ea6d01853d6262c278e9196246597153c97d9

**Comment by xcatliu** [comment]
BTW, you cannot write code like

```js
export xx from 'xxx';
```

It should be something like this:

```js
export * from 'xxx';
```

or this:

```js
export { xx } from 'xxx';
export { yy as yyy } from 'yyy';
```

**Comment by xcatliu** [comment]
It's better if you can beautify you issue content by using correct format of markdown.

Here is a guide: https://guides.github.com/features/mastering-markdown/

**Comment by xcatliu** [comment]
Related post: http://www.aliued.com/?p=3240

**Comment by nanjixiong218** [comment]
Thanks for your feedback, I got it, the next time i will beautify my issue ☺
