### ISSUE TITLE
IE8 Object.defineproperty 问题

### ISSUE THREAD

**Issue by Prometheuser** [xcatliu/react-ie8#34]
目前错误信息，了解到是某个地方使用了Object.defineproperty，但是我已经重构了代码应该没有这种问题，极有可能是依赖的第三方库的问题，我已经手动改了报错的库例如react-router-redux，并且已经把明确不支持IE8的库要么取消要么降级到支持的版本。现在的错误信息完全没有办法定位到错误。

![image](https://cloud.githubusercontent.com/assets/13377095/15805890/4f21f158-2b69-11e6-9409-cfe5c663a385.png)

babelrc

![image](https://cloud.githubusercontent.com/assets/13377095/15805894/5e1c32d6-2b69-11e6-86d9-722b3dd5deb8.png)

webpack loaders

![image](https://cloud.githubusercontent.com/assets/13377095/15805907/8c77dd74-2b69-11e6-928b-bb1f6bd376e1.png)

entry.index.js

![image](https://cloud.githubusercontent.com/assets/13377095/15805910/9acfc2e2-2b69-11e6-8a4e-acd08b03dec4.png)

代码片段如上，如果还需要什么信息我再提供。还请大家帮忙看一下问题，已经愁了我好几天，google都翻烂了，错误信息的位置在core-js，完全没有头绪，感激不尽，感激不尽。

**Comment by xcatliu** [comment]
我可能只能通过我的经验给点建议哈：

- 报错的地方通过错误栈定位到是哪儿有问题
- 打包好的 js 文件，可以搜索到使用了 `Object.defineproperty` 并且里面使用了 `get` 的地方吗？如果搜得到就可以定位到是哪个第三方库的问题了
- 逐个减少依赖，最终生成一个「最小报错代码」

**Comment by xcatliu** [comment]
`Object.defineproperty` 相关的问题：
https://github.com/xcatliu/react-ie8/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AObject.defineproperty+

**Comment by Prometheuser** [comment]
好的，我先尝试一下！感谢！

**Comment by Prometheuser** [comment]
感谢 问题已经解决，通过错误栈定位并修改了几个不兼容的库。
＊react-router要用2.0.1
修改的库已上传至npm，如果有需要可以来看看
https://www.npmjs.com/~tengchiayueh

**Comment by xcatliu** [comment]
Good!
