### ISSUE TITLE
Page renders with amoral latency, like minute or two, and appears only after updating page

### ISSUE THREAD

**Issue by league55** [xcatliu/react-ie8#35]
Header and background defined out of react stuff appear at once, but all inside reacts "render" method needs too much time. But after everything rendered ALL pages work like they should, I mean at first nothing shown, then you can go from page to page and all is fast. This appears only in pure IE8, in IE9 compatibility mode all OK.

**Comment by xcatliu** [comment]
IE8 is mach slow than you think, but one minute is intolerable.

Is there any error messages?
Is the issue happened occasionally or always?
Was page slow when your project is not that big?

It's hard to help you if I can't reach the code.
I think you can try to delete half of your code, and see if the page still slow. Then delete half of remaining code again, then half... until you find the key point of slowing the page.

**Comment by league55** [comment]
no error messages, it happens always.
project is not big, like 3 pages. I can open any of them via url and none is shown, but after any appears everything becomes fast and I can open any page immediately.
I'll try what you proposed.

**Comment by league55** [comment]
I'm a bit shocked but it appears after I open dev tools...
no render... no render.... I open dev tools -> renders

**Comment by league55** [comment]
...and I think, I found solution
http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once

sorry for taking time. I work on this fix for few days...

**Comment by xcatliu** [comment]
Oops, did you forget to add the `require('console-polyfill');` ?

**Comment by league55** [comment]
thank you!!!
