### ISSUE TITLE
在chunk中出现了 default 关键字。

### ISSUE THREAD

**Issue by gagayang** [xcatliu/react-ie8#38]
我已经使用了es3ify-loader但是在 chunk文件中还是发现有default 关键字。这个问题怎么解决呢

**Comment by xcatliu** [comment]
简单的方式可以用 uglifyjs 压缩，压缩之后就没有 `default` 关键字了
复杂的方式就慢慢 debug 看看为什么会还有 `default`

**Comment by gagayang** [comment]
恩 我试试 我用es3ify-loader 之后发现 主文件是没有default关键字了，但是渐进加载的chunk还是有。我先压缩混淆下试试。谢谢了
